index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

create:
    path: /people
    defaults:
        _controller: person.controller:createAction
        _format: json
    methods: [POST]

put:
    path: /people
    defaults:
        _controller: person.controller:putAction
        _format: json
    methods: [PUT, PATCH]

update:
    path: /people/{id}
    defaults:
        _controller: person.controller:updateAction
        _format: json
    methods: [PUT, PATCH]

delete:
    path: /people/{id}
    defaults:
        _controller: person.controller:deleteAction
        _format: json
    methods: [DELETE]

get:
    path: /people/{id}
    defaults:
        _controller: person.controller:getAction
        _format: json
    methods: [GET]
